title: <p align="center"> Fabrizio Cominetti </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="documents/CV-FabrizioCominetti-online.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/fabriziocominetti/">LinkedIn</a> |
  <a href="https://github.com/fabriziocominetti">GitHub</a>
  </p>
  
  <p align="justify">
  Hi Everyone! ðŸ‘‹ Welcome to <b><i>Fabrizio Cominetti</i></b>'s portfolio website
  <br>
  <ul>
  <li>ðŸ“Œ Data Science at <b>University of Milano-Bicocca</b></li>
  <li>ðŸ“Œ Digital Editor Intern at <b>AC Milan</b></li>
  </ul>
  <p align="center">
  <a href="https://linktr.ee/fabriziocominetti">LinkTree</a>
  </p>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-8Q75V2KGYQ # Google Analytics tracking ID